create table if not exists dresses (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null,
  type text,
  size text,
  color text,
  color_hex text,
  stock integer default 0,
  sold integer default 0,
  vendor text,
  price numeric default 0,
  old_price numeric,
  rating integer default 4,
  sale boolean default false,
  image_url text,
  created_at timestamp with time zone default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text not null,
  customer_name text not null,
  items integer default 0,
  total numeric default 0,
  date_text text,
  order_date date,
  line_items jsonb default '[]'::jsonb,
  names text,
  created_at timestamp with time zone default now()
);

alter table dresses enable row level security;
alter table orders enable row level security;

drop policy if exists "Allow public read dresses" on dresses;
drop policy if exists "Allow public insert dresses" on dresses;
drop policy if exists "Allow public update dresses" on dresses;
drop policy if exists "Allow public read orders" on orders;
drop policy if exists "Allow public insert orders" on orders;

create policy "Allow public read dresses"
on dresses for select
using (true);

create policy "Allow public insert dresses"
on dresses for insert
with check (true);

create policy "Allow public update dresses"
on dresses for update
using (true)
with check (true);

create policy "Allow public read orders"
on orders for select
using (true);

create policy "Allow public insert orders"
on orders for insert
with check (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'dresses'
  ) then
    alter publication supabase_realtime add table dresses;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table orders;
  end if;
end $$;
